### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by gewaechshaus** [zsoerenm/magento2-optionaltelephone#1]
Hey,

i am getting the following error while compiling

`
Fatal error:  Cannot declare class Zorn\OptionalTelephone\Model\Address\AbstractAddress\Plugin, because the name is already in use in /var/www/html/vendor/zsoerenm/magento2-optionaltelephone/Model/Order/Address/Validator/Plugin.php on line 4`

http://devdocs.magento.com/guides/v2.0/extension-dev-guide/plugins.html
https://github.com/magento/magento2-samples/tree/master/sample-module-interception

Viele Grüße
Jan

**Comment by zsoerenm** [comment]
Hallo,

I'm sorry for the late reply. I didn't get an email notification. The bug should be fixed now in v.1.2.1. Just update with composer.

Viele Grüße
Sören
