### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by lfritsche** [zsoerenm/magento2-optionaltelephone#3]
Hi @zsoerenm ,

Running Magento 2.0.12 compilation I get the following Error:

[ReflectionException]                                 
  Class \Zorn\Telephone\Setup\Uninstall does not exist 

Any ideas?
Thank you very much for your extension.
Everything else works fine.

**Comment by zsoerenm** [comment]
There was a namespace error. Thanks for pointing that out. It should be fixed in the newest release.

**Comment by lfritsche** [comment]
Great - thank you @zsoerenm.
Tested it > everything fine by now.
