### ISSUE TITLE
manual install without composer? 

### ISSUE THREAD

**Issue by Jacob-Wilsons** [zsoerenm/magento2-optionaltelephone#4]
Hello, it is a question, (not an issue). Just didn't see the option to write it 

**Can this plugin be installed manually, without the Composer?**

If yes, is this the correct folder that I need to create for the plugin content?

> {Magento root}/app/code/optionaltelephone/

Thank You!

**Comment by zsoerenm** [comment]
No without composer it should be installed in:
{Magento root}/app/code/Zorn/OptionalTelephone/
I updated the Readme.md to include the info. Let me now if does not work for you

**Comment by Jacob-Wilsons** [comment]
Worked like a champ, Thank You @zsoerenm
