### ISSUE TITLE
Not working in Magento version: 2.1.8

### ISSUE THREAD

**Issue by namratavora** [zsoerenm/magento2-optionaltelephone#5]
**Exception #0 (Magento\Framework\Exception\LocalizedException): Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory.** 
Giving above exception on front-end

**Refer detailed error on front-end:**
```
1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory. 
The following modules are outdated:
Magento_Catalog schema: current version - 2.1.4, required version - 2.1.3
Magento_Catalog data: current version - 2.1.4, required version - 2.1.3
Magento_Quote schema: current version - 2.0.4, required version - 2.0.3
Magento_Quote data: current version - 2.0.4, required version - 2.0.3
Magento_Integration schema: current version - 2.2.0, required version - 2.0.1
Magento_Integration data: current version - 2.2.0, required version - 2.0.1
```

**Comment by zsoerenm** [comment]
you probably forgot to run

```bin/magento setup:upgrade```

from the Magento root directory.

**Comment by namratavora** [comment]
Yes, I run `php bin/magento setup:upgrade` for multiple times.
I installed this module using composer. While i uninstalled it, It is giving me below error:

Removing data of Zorn_OptionalTelephone
Recoverable Error: Argument 1 passed to Magento\Eav\Setup\EavSetup::__construct() must implement interface Magento\Framework\Setup\ModuleDataSetupInterface, instance of Magento\Setup\Module\Setup given, called in /var/www/html/test/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93 and defined in /var/www/html/ilnp2_latest/vendor/magento/module-eav/Setup/EavSetup.php on line 87
Please disable maintenance mode after you resolved above issues

It degraded my magento from **2.1.8** version to **2.1.5**

**Comment by zsoerenm** [comment]
I have a look this weekend

**Comment by zsoerenm** [comment]
I made a new fresh 2.1.8 install and everything seems to work just fine. Can you test it on a new installation?

**Comment by namratavora** [comment]
Sure, I'll take a try and let you know :)

**Comment by namratavora** [comment]
Hello,

Sorry for late reply, Your module is working perfectly, Issue was with one of the existing third-party module in my magento installation. Good Job :+1: 

Thanks

**Comment by gerbesf** [comment]
working fine in 2.2.7
